### ISSUE TITLE
Final Notes

### ISSUE THREAD

**Issue by stecklow** [ayyubibrahimi/us-post-data#22]
- [ ] Please capitalize data

- [ ] Please order columns:

- UID
- First name
- Last name
- If demographic info exists
- Start/end dates
- Employers
- Reason for separation if exists

- [ ] Please add to dropdown:

- Georgia Discipline
- Oregon
- South Carolina
- Idaho

- [ ] Please have "National Police Index" header bring you back home

- [ ] Birth year decimals:

- Florida has a birth year decimal
- Kentucky has a birth year decimal
- Ohio has a birth year decimal

- [ ] Tennessee "reason for separation" should be "employment change"
- [ ] Utah "reason for separation" should be "employment status"
- [ ] Vermont "reason for separation" should be "employment change"
- [ ] Wyoming "reason for separation" should be "employment status"

Holding for launch:

- [ ] New Mexico

On further review, I think we should keep Maryland. It's ok that it might show multiple rows within the same department for an officer and that it's a little inconsistent with the other states. It's still useful and accurate.

**Comment by ayyubibrahimi** [comment]
Done except for column order. We should re-discuss column order bc of the inclusion of discipline data for GA and FL.

**Comment by stecklow** [comment]
New items noticed week of:

- [ ] Dropdown cuts off the bottom, doesn't allow for scrolling down
- [ ] I still see birth year decimals for Kentucky, Ohio
